services:
  - type: web
    name: lumbung-ilmu
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: APP_NAME
        value: Lumbung Ilmu
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: APP_TIMEZONE
        value: Asia/Jakarta
      - key: DATABASE_URL
        fromDatabase:
          name: lumbung-ilmu
          property: connectionString
      - key: DB_CONNECTION
        value: pgsql

databases:
  - name: lumbung-ilmu
    plan: free
